name: Testing and Deploying WEB App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_unit_tests:
    runs-on: ubuntu-latest
    

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js version 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    - name: Run npm install
      run: npm install
    - name: Run unit tests
      run: npm run test:unit
    - name: Display name
      run: echo "KristiyqnPisev"
  
